### ISSUE TITLE
OpenAI Gym Issue

### ISSUE THREAD

**Issue by zhefan** [prasoongoyal/rl-lang-action-reward-network#2]
Hi, really nice work! I am trying to run your code.

After installation and training (both successful), I cannot run your test code. 
Here's my command:
`python rl/main.py --lang_coeff=1.0 --lang_enc=onehot --model_dir=./learn_model --expt_id=2 --descr_id=1`
Here's the error message:
`terminate called after throwing an instance of 'char const*'
Aborted (core dumped)`
I traced the code, and it failed at https://github.com/prasoongoyal/rl-learn/blob/a43b415749190cfefa89d8a4642d0940a53e7a29/rl/environment.py#L78
as it tries to load a saved state. This might be an OpenAI Gym issue.
Since you did not specify OpenAI Gym version in the requirements.txt, I wonder which version did you use?

**Comment by duzani** [comment]
HI, I'm having exactly the same problem!
Did you find out the solution?

**Comment by zhefan** [comment]
Thank @prasoongoyal for his answer. gym==0.10.5 and atari-py==0.1.1 are the proper versions for OpenAI Gym env. If atari-py cannot be installed, try `sudo apt-get install zlib1g-dev` first.

**Comment by zhefan** [comment]
Hi,

     I just updated the issue. Please take a look.

Best,

**Comment by prasoongoyal** [comment]
Awesome, thanks for letting me know! I'll update the README.
ᐧ
